#!/usr/bin/env python3
"""
Generate LangChain/CrewAI tool definitions from OpenAPI spec.

Reads openapi-unified.json and outputs LangChain-compatible tool classes
to bridges/langchain/selemene_tools.py.
"""

import json
import os
import re
import sys
from pathlib import Path


PYTHON_TEMPLATE = '''"""Auto-generated Selemene Engine tools for LangChain/CrewAI.
Generated by scripts/generate-langchain-tools.py from OpenAPI spec.
"""

import httpx
import os
from typing import Optional, Any
from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool


RUST_URL = os.environ.get("SELEMENE_RUST_URL", "http://localhost:8080")
TS_URL = os.environ.get("SELEMENE_TS_URL", "http://localhost:3001")
API_KEY = os.environ.get("SELEMENE_API_KEY", "")


def _headers() -> dict:
    """Build request headers with optional API key."""
    h = {"Content-Type": "application/json"}
    if API_KEY:
        h["Authorization"] = f"Bearer {{API_KEY}}"
    return h


def _get(url: str, params: dict = None) -> dict:
    """Execute GET request."""
    with httpx.Client(timeout=30.0) as client:
        r = client.get(url, headers=_headers(), params=params)
        r.raise_for_status()
        return r.json()


def _post(url: str, body: dict) -> dict:
    """Execute POST request."""
    with httpx.Client(timeout=30.0) as client:
        r = client.post(url, headers=_headers(), json=body)
        r.raise_for_status()
        return r.json()


# --- Input Schemas ---

{input_schemas}

# --- Tool Functions ---

{tool_functions}

# --- StructuredTool instances ---

{structured_tools}

def get_all_tools() -> list:
    """Return all Selemene tools for LangChain/CrewAI."""
    return [{tool_names}]
'''


def path_to_snake_case(path: str, method: str) -> str:
    """Convert OpenAPI path to snake_case tool name."""
    # Remove leading slash and /api/v1 prefix
    clean = re.sub(r'^/api/v\d+/', '', path)
    clean = re.sub(r'^/ts/', 'ts_', clean)
    clean = clean.lstrip('/')

    # Replace path params {id} with generic name
    clean = re.sub(r'\{[^}]+\}', '', clean)

    # Replace slashes and hyphens with underscores
    clean = re.sub(r'[/-]', '_', clean)

    # Remove duplicate underscores and trailing underscores
    clean = re.sub(r'_+', '_', clean)
    clean = clean.strip('_')

    # If empty (e.g., /health), use the last part of original path
    if not clean:
        clean = path.split('/')[-1] or 'root'

    # Add prefix based on route origin
    if '/ts/' in path:
        prefix = 'selemene_ts_'
    else:
        prefix = 'selemene_'

    return prefix + clean.lower()


def python_type_from_schema(schema: dict) -> str:
    """Convert JSON schema type to Python type hint."""
    schema_type = schema.get('type', 'string')
    type_map = {
        'string': 'str',
        'integer': 'int',
        'number': 'float',
        'boolean': 'bool',
        'object': 'dict',
        'array': 'list',
    }
    return type_map.get(schema_type, 'Any')


def build_input_schema_class(tool_name: str, params: list, body_schema: dict) -> tuple[str, str]:
    """Build Pydantic input schema class for a tool."""
    class_name = ''.join(word.capitalize() for word in tool_name.split('_')) + 'Input'

    fields = []

    # Add path parameters
    for param in params:
        if param.get('in') == 'path':
            name = param['name']
            py_type = python_type_from_schema(param.get('schema', {'type': 'string'}))
            desc = param.get('description', f"{name} parameter")
            fields.append(f'    {name}: {py_type} = Field(description="{desc}")')

    # Add query parameters
    for param in params:
        if param.get('in') == 'query':
            name = param['name']
            py_type = python_type_from_schema(param.get('schema', {'type': 'string'}))
            desc = param.get('description', f"{name} parameter")
            required = param.get('required', False)
            if required:
                fields.append(f'    {name}: {py_type} = Field(description="{desc}")')
            else:
                fields.append(f'    {name}: Optional[{py_type}] = Field(None, description="{desc}")')

    # Add body parameters if present
    if body_schema and 'properties' in body_schema:
        for prop_name, prop_schema in body_schema['properties'].items():
            py_type = python_type_from_schema(prop_schema)
            desc = prop_schema.get('description', f"{prop_name} parameter")
            required_list = body_schema.get('required', [])
            if prop_name in required_list:
                fields.append(f'    {prop_name}: {py_type} = Field(description="{desc}")')
            else:
                fields.append(f'    {prop_name}: Optional[{py_type}] = Field(None, description="{desc}")')

    if not fields:
        # No parameters - return empty class
        return class_name, f"class {class_name}(BaseModel):\n    pass\n"

    schema_def = f"class {class_name}(BaseModel):\n" + '\n'.join(fields) + '\n'
    return class_name, schema_def


def build_function(tool_name: str, path: str, method: str, params: list, body_schema: dict, description: str) -> str:
    """Build the tool function implementation."""
    func_name = tool_name.replace('selemene_', '').replace('selemene_ts_', '')

    # Determine base URL
    base_url = 'TS_URL' if '/ts/' in path else 'RUST_URL'

    # Build function signature
    param_names = []
    param_defs = []

    for param in params:
        name = param['name']
        py_type = python_type_from_schema(param.get('schema', {'type': 'string'}))
        required = param.get('required', False)
        if required:
            param_defs.append(f"{name}: {py_type}")
        else:
            param_defs.append(f"{name}: Optional[{py_type}] = None")
        param_names.append(name)

    if body_schema and 'properties' in body_schema:
        for prop_name, prop_schema in body_schema['properties'].items():
            py_type = python_type_from_schema(prop_schema)
            required_list = body_schema.get('required', [])
            if prop_name in required_list:
                param_defs.append(f"{prop_name}: {py_type}")
            else:
                param_defs.append(f"{prop_name}: Optional[{py_type}] = None")
            param_names.append(prop_name)

    signature = f"def {func_name}({', '.join(param_defs) if param_defs else ''}) -> dict:"

    # Build function body
    # Replace path parameters in URL
    url_path = path
    path_params = [p for p in params if p.get('in') == 'path']
    for p in path_params:
        pname = p['name']
        url_path = url_path.replace('{' + pname + '}', f'{{{pname}}}')

    url_line = f'    url = f"{{{base_URL}}}{url_path}"'

    if method.upper() == 'GET':
        # Build query params dict
        query_params = [p for p in params if p.get('in') == 'query']
        if query_params:
            param_dict_items = [f'"{p["name"]}": {p["name"]}' for p in query_params]
            params_line = f'    params = {{{", ".join(param_dict_items)}}}'
            return_line = '    return _get(url, params=params)'
            return f'{signature}\n    """{description}"""\n{url_line}\n{params_line}\n{return_line}\n'
        else:
            return_line = '    return _get(url)'
            return f'{signature}\n    """{description}"""\n{url_line}\n{return_line}\n'
    else:
        # POST - build body
        if body_schema and 'properties' in body_schema:
            body_items = [f'"{prop}": {prop}' for prop in body_schema['properties'].keys()]
            body_line = f'    body = {{{", ".join(body_items)}}}'
            return_line = '    return _post(url, body)'
            return f'{signature}\n    """{description}"""\n{url_line}\n{body_line}\n{return_line}\n'
        else:
            return_line = '    return _post(url, {{}})'
            return f'{signature}\n    """{description}"""\n{url_line}\n{return_line}\n'


def build_structured_tool(tool_name: str, func_name: str, description: str, input_class: str, has_params: bool) -> str:
    """Build StructuredTool definition."""
    clean_func_name = func_name.replace('selemene_', '').replace('selemene_ts_', '')
    tool_var_name = tool_name + '_tool'

    if has_params:
        return f'''{tool_var_name} = StructuredTool.from_function(
    func={clean_func_name},
    name="{tool_name}",
    description="{description}",
    args_schema={input_class},
)
'''
    else:
        return f'''{tool_var_name} = StructuredTool.from_function(
    func={clean_func_name},
    name="{tool_name}",
    description="{description}",
)
'''


def generate_langchain_tools(openapi_path: str) -> str:
    """Generate LangChain tools Python module from OpenAPI spec."""
    with open(openapi_path, 'r') as f:
        spec = json.load(f)

    input_schemas = []
    tool_functions = []
    structured_tools = []
    tool_names = []

    for path, path_item in spec.get('paths', {}).items():
        for method, operation in path_item.items():
            if method not in ['get', 'post', 'put', 'patch', 'delete']:
                continue

            # Extract parameters
            params = operation.get('parameters', [])

            # Extract request body schema
            body_schema = {}
            if 'requestBody' in operation:
                content = operation['requestBody'].get('content', {})
                json_content = content.get('application/json', {})
                body_schema = json_content.get('schema', {})

            # Build tool name and description
            tool_name = path_to_snake_case(path, method)
            description = operation.get('summary') or operation.get('description') or f"{method.upper()} {path}"

            # Build input schema class
            input_class_name, input_class_def = build_input_schema_class(tool_name, params, body_schema)
            has_params = bool(params or (body_schema and 'properties' in body_schema))

            if has_params:
                input_schemas.append(input_class_def)

            # Build function
            func_def = build_function(tool_name, path, method, params, body_schema, description)
            tool_functions.append(func_def)

            # Build StructuredTool
            tool_def = build_structured_tool(tool_name, tool_name, description, input_class_name, has_params)
            structured_tools.append(tool_def)

            tool_names.append(f'{tool_name}_tool')

    # Build final module
    return PYTHON_TEMPLATE.format(
        input_schemas='\n'.join(input_schemas) if input_schemas else '# No input schemas needed\n',
        tool_functions='\n'.join(tool_functions),
        structured_tools='\n'.join(structured_tools),
        tool_names=', '.join(tool_names),
    )


def main():
    # Determine input and output paths
    project_root = Path(__file__).parent.parent
    input_path = project_root / 'openapi-unified.json'
    output_path = project_root / 'bridges' / 'langchain' / 'selemene_tools.py'

    # Check for --input flag
    if len(sys.argv) > 2 and sys.argv[1] == '--input':
        input_path = Path(sys.argv[2])

    if not input_path.exists():
        print(f"ERROR: OpenAPI spec not found at {input_path}", file=sys.stderr)
        print("Run from project root or use --input flag to specify path", file=sys.stderr)
        sys.exit(1)

    # Generate tools
    tools_module = generate_langchain_tools(str(input_path))

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    with open(output_path, 'w') as f:
        f.write(tools_module)

    print(f"✓ Generated LangChain tools from {input_path}")
    print(f"✓ Written to {output_path}")


if __name__ == '__main__':
    main()
