name = "selemene-llm-proxy"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[kv_namespaces]]
binding = "LLM_SECRETS"
id = "310ee556e91d465eb54d55586a541e49"
preview_id = "ab6f688eed234a0c9648920921d21ed7"