#!/usr/bin/env bash
# Sync task-master style JSON plans in docs/planning/ to GitHub Issues.
#
# Features:
# - Idempotent upsert using plan-task-id marker in issue body
# - Optional close/reopen based on task.status (completed/done/closed)
# - Dynamic labels for plan/phase/sprint/wave/area
# - Optional add to GitHub Project (if owner + project number provided)

set -euo pipefail

APPLY=false
REPO="${GITHUB_REPOSITORY:-}"
PLAN_GLOB="docs/planning/*.json"
PLAN_FILE=""
PHASE_FILTER=""
PROJECT_OWNER="${GITHUB_REPOSITORY_OWNER:-}"
PROJECT_NUMBER=""
SLEEP_SECONDS="0.15"

usage() {
  cat <<'EOF'
Usage:
  scripts/sync-plans-to-github-issues.sh [options]

Options:
  --apply                      Apply changes (default is dry-run)
  --repo <owner/repo>          GitHub repo (default: $GITHUB_REPOSITORY)
  --plan-file <path>           Single plan file to sync
  --plan-glob <glob>           Glob of plan files (default: docs/planning/*.json)
  --phase-filter <csv>         Comma-separated phase_ids to sync (example: P0,P1)
  --project-owner <owner>      GitHub owner for project item add (optional)
  --project-number <number>    GitHub Project number (optional)
  --sleep-seconds <float>      Delay between API operations (default: 0.15)
  --help                       Show help

Notes:
  - Task identity is tracked via "plan-task-id: <id>" marker in issue body.
  - If task.status is one of completed|done|closed, issue is closed.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)
      APPLY=true
      shift
      ;;
    --repo)
      REPO="${2:-}"
      shift 2
      ;;
    --plan-file)
      PLAN_FILE="${2:-}"
      shift 2
      ;;
    --plan-glob)
      PLAN_GLOB="${2:-}"
      shift 2
      ;;
    --phase-filter)
      PHASE_FILTER="${2:-}"
      shift 2
      ;;
    --project-owner)
      PROJECT_OWNER="${2:-}"
      shift 2
      ;;
    --project-number)
      PROJECT_NUMBER="${2:-}"
      shift 2
      ;;
    --sleep-seconds)
      SLEEP_SECONDS="${2:-0.15}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$REPO" ]]; then
  echo "Error: repo is required (pass --repo or set GITHUB_REPOSITORY)." >&2
  exit 1
fi

for bin in gh jq; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "Error: required binary '$bin' not found." >&2
    exit 1
  fi
done

slugify() {
  local raw="$1"
  echo "$raw" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g'
}

contains_csv() {
  local value="$1"
  local csv="$2"
  if [[ -z "$csv" ]]; then
    return 0
  fi
  IFS=',' read -r -a items <<< "$csv"
  for item in "${items[@]}"; do
    if [[ "$(echo "$item" | xargs)" == "$value" ]]; then
      return 0
    fi
  done
  return 1
}

ensure_label() {
  local name="$1"
  local color="${2:-1f6feb}"
  local desc="${3:-Generated by plan sync automation}"
  if [[ "$APPLY" != true ]]; then
    return 0
  fi
  gh label create "$name" --repo "$REPO" --color "$color" --description "$desc" --force >/dev/null 2>&1 || true
}

find_issue_number_by_task_id() {
  local task_id="$1"
  gh issue list \
    --repo "$REPO" \
    --state all \
    --search "\"plan-task-id: ${task_id}\" in:body" \
    --limit 1 \
    --json number \
    --jq '.[0].number // empty'
}

issue_url_by_number() {
  local number="$1"
  gh issue view "$number" --repo "$REPO" --json url --jq '.url'
}

task_state_is_done() {
  local status="$(echo "${1:-}" | tr '[:upper:]' '[:lower:]')"
  [[ "$status" == "completed" || "$status" == "done" || "$status" == "closed" ]]
}

build_plan_files() {
  if [[ -n "$PLAN_FILE" ]]; then
    if [[ ! -f "$PLAN_FILE" ]]; then
      echo "Error: plan file not found: $PLAN_FILE" >&2
      exit 1
    fi
    printf '%s\n' "$PLAN_FILE"
    return
  fi

  # shellcheck disable=SC2086
  compgen -G "$PLAN_GLOB" || true
}

echo "Plan sync start"
echo "  repo: $REPO"
echo "  mode: $([[ "$APPLY" == true ]] && echo apply || echo dry-run)"
echo "  plan-glob: ${PLAN_FILE:-$PLAN_GLOB}"
echo "  phase-filter: ${PHASE_FILTER:-<none>}"

ensure_label "plan-sync" "5319e7" "Created/managed by plan sync automation"
ensure_label "roadmap" "0e8a16" "Roadmap planning task"

mapfile -t PLAN_FILES < <(build_plan_files)
if [[ ${#PLAN_FILES[@]} -eq 0 ]]; then
  echo "No plan files matched."
  exit 0
fi

for plan_file in "${PLAN_FILES[@]}"; do
  echo ""
  echo "Processing plan: $plan_file"

  plan_name="$(jq -r '.project.name // "Unknown Plan"' "$plan_file")"
  plan_basename="$(basename "$plan_file")"
  plan_slug="plan-$(slugify "${plan_basename%.json}")"
  ensure_label "$plan_slug" "1f6feb" "Tasks sourced from ${plan_basename}"

  row_count="$(jq '[.phases[] as $p | $p.sprints[] as $s | $s.tasks[]] | length' "$plan_file")"
  echo "  task rows: $row_count"

  jq -c --arg plan_file "$plan_file" --arg plan_name "$plan_name" '
    .phases[] as $p
    | $p.sprints[] as $s
    | $s.tasks[]
    | {
        plan_file: $plan_file,
        plan_name: $plan_name,
        phase_id: $p.phase_id,
        phase_name: $p.name,
        phase_objective: $p.objective,
        sprint_id: $s.sprint_id,
        sprint_focus: $s.focus,
        task: .
      }
  ' "$plan_file" | while IFS= read -r row; do
    task_id="$(echo "$row" | jq -r '.task.id')"
    title="$(echo "$row" | jq -r '.task.title')"
    area="$(echo "$row" | jq -r '.task.area // "general"')"
    owner_role="$(echo "$row" | jq -r '.task.owner_role // "unassigned"')"
    est_hours="$(echo "$row" | jq -r '.task.est_hours // "n/a"')"
    deliverable="$(echo "$row" | jq -r '.task.deliverable // ""')"
    acceptance="$(echo "$row" | jq -r '.task.acceptance // ""')"
    status="$(echo "$row" | jq -r '.task.status // "planned"')"
    phase_id="$(echo "$row" | jq -r '.phase_id')"
    phase_name="$(echo "$row" | jq -r '.phase_name')"
    phase_objective="$(echo "$row" | jq -r '.phase_objective // ""')"
    sprint_id="$(echo "$row" | jq -r '.sprint_id')"
    sprint_focus="$(echo "$row" | jq -r '.sprint_focus // ""')"

    if ! contains_csv "$phase_id" "$PHASE_FILTER"; then
      continue
    fi

    deps_md="$(echo "$row" | jq -r '
      .task.dependencies // [] |
      if length == 0 then "- None"
      else map("- `" + . + "`") | join("\n")
      end
    ')"

    wave_n="$(echo "$phase_name" | sed -nE 's/.*[Ww]ave[[:space:]]+([0-9]+).*/\1/p')"
    wave_label=""
    if [[ -n "$wave_n" ]]; then
      wave_label="wave-w${wave_n}"
      ensure_label "$wave_label" "fbca04" "Wave ${wave_n}"
    fi

    phase_label="phase-$(slugify "$phase_id")"
    sprint_label="sprint-$(slugify "$sprint_id")"
    area_label="area-$(slugify "$area")"
    owner_label="owner-$(slugify "$owner_role")"
    ensure_label "$phase_label" "d4c5f9" "Phase ${phase_id}"
    ensure_label "$sprint_label" "bfdadc" "Sprint ${sprint_id}"
    ensure_label "$area_label" "c2e0c6" "Task area ${area}"
    ensure_label "$owner_label" "f9d0c4" "Owner role ${owner_role}"

    issue_title="[${task_id}] ${title}"

    body_file="$(mktemp)"
    {
      echo "<!-- plan-sync: v1 -->"
      echo "<!-- plan-file: ${plan_file} -->"
      echo "<!-- plan-task-id: ${task_id} -->"
      echo "<!-- phase-id: ${phase_id} -->"
      echo "<!-- sprint-id: ${sprint_id} -->"
      echo ""
      echo "## Summary"
      echo "${title}"
      echo ""
      echo "## Plan Context"
      echo "- Plan: \`${plan_name}\`"
      echo "- Phase: \`${phase_id}\` (${phase_name})"
      echo "- Sprint: \`${sprint_id}\`"
      echo "- Area: \`${area}\`"
      echo "- Owner Role: \`${owner_role}\`"
      echo "- Estimated Hours: \`${est_hours}\`"
      echo "- Status (plan): \`${status}\`"
      echo ""
      if [[ -n "$phase_objective" ]]; then
        echo "## Phase Objective"
        echo "${phase_objective}"
        echo ""
      fi
      if [[ -n "$sprint_focus" ]]; then
        echo "## Sprint Focus"
        echo "${sprint_focus}"
        echo ""
      fi
      echo "## Deliverable"
      echo "${deliverable:-N/A}"
      echo ""
      echo "## Acceptance"
      echo "${acceptance:-N/A}"
      echo ""
      echo "## Dependencies"
      echo "${deps_md}"
      echo ""
      echo "## Sync Notes"
      echo "- Source file: \`${plan_file}\`"
      echo "- Managed by: \`scripts/sync-plans-to-github-issues.sh\`"
      echo "- To auto-close, set \`task.status\` to \`completed\` in the plan."
    } > "$body_file"

    issue_number="$(find_issue_number_by_task_id "$task_id")"
    label_csv="plan-sync,roadmap,${plan_slug},${phase_label},${sprint_label},${area_label},${owner_label}"
    if [[ -n "$wave_label" ]]; then
      label_csv="${label_csv},${wave_label}"
    fi

    if [[ -z "$issue_number" ]]; then
      if [[ "$APPLY" == true ]]; then
        echo "  create: ${issue_title}"
        created_url="$(
          gh issue create \
            --repo "$REPO" \
            --title "$issue_title" \
            --body-file "$body_file" \
            --label "$label_csv"
        )"
        issue_number="$(echo "$created_url" | sed -nE 's#.*/issues/([0-9]+)$#\1#p')"
      else
        echo "  dry-run create: ${issue_title}"
        issue_number=""
      fi
    else
      if [[ "$APPLY" == true ]]; then
        echo "  update: #${issue_number} ${issue_title}"
        gh issue edit "$issue_number" --repo "$REPO" --title "$issue_title" --body-file "$body_file" >/dev/null
        gh issue edit "$issue_number" --repo "$REPO" --add-label "$label_csv" >/dev/null
      else
        echo "  dry-run update: #${issue_number} ${issue_title}"
      fi
    fi

    if [[ "$APPLY" == true && -n "$issue_number" ]]; then
      current_state="$(gh issue view "$issue_number" --repo "$REPO" --json state --jq '.state' | tr '[:upper:]' '[:lower:]')"
      if task_state_is_done "$status"; then
        if [[ "$current_state" != "closed" ]]; then
          gh issue close "$issue_number" --repo "$REPO" --comment "Closing via plan sync: task status is '${status}'." >/dev/null
          echo "    closed: #${issue_number} (status=${status})"
        fi
      else
        if [[ "$current_state" == "closed" ]]; then
          gh issue reopen "$issue_number" --repo "$REPO" >/dev/null
          echo "    reopened: #${issue_number} (status=${status})"
        fi
      fi
    fi

    if [[ "$APPLY" == true && -n "$PROJECT_NUMBER" && -n "$PROJECT_OWNER" && -n "$issue_number" ]]; then
      issue_url="$(issue_url_by_number "$issue_number")"
      gh project item-add "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --url "$issue_url" >/dev/null 2>&1 || true
    fi

    rm -f "$body_file"
    sleep "$SLEEP_SECONDS"
  done
done

echo ""
echo "Plan sync complete."
