// Static rasa + dosha metadata for all 72 melakartas.
// Extracted from data/nadabrahman/melakarta_ragas.json — avoids a runtime
// JSON import that would require the data directory to be inside the Next.js
// project root. Update if the JSON source changes.

export interface RagaMeta { rasa: string; dosha: string; }

export const RAGA_META: Readonly<Record<number, RagaMeta>> = {
  1: { rasa: "shanta", dosha: "vata" },
  2: { rasa: "adbhuta", dosha: "vata" },
  3: { rasa: "bhakti", dosha: "kapha" },
  4: { rasa: "shanta", dosha: "kapha" },
  5: { rasa: "karuna", dosha: "pitta" },
  6: { rasa: "shanta", dosha: "vata" },
  7: { rasa: "veera", dosha: "pitta" },
  8: { rasa: "karuna", dosha: "kapha" },
  9: { rasa: "karuna", dosha: "kapha" },
  10: { rasa: "raudra", dosha: "pitta" },
  11: { rasa: "shringara", dosha: "kapha" },
  12: { rasa: "shringara", dosha: "pitta" },
  13: { rasa: "veera", dosha: "pitta" },
  14: { rasa: "bhakti", dosha: "kapha" },
  15: { rasa: "shanta", dosha: "vata" },
  16: { rasa: "shringara", dosha: "pitta" },
  17: { rasa: "veera", dosha: "pitta" },
  18: { rasa: "adbhuta", dosha: "vata" },
  19: { rasa: "adbhuta", dosha: "vata" },
  20: { rasa: "karuna", dosha: "kapha" },
  21: { rasa: "raudra", dosha: "pitta" },
  22: { rasa: "bhakti", dosha: "vata" },
  23: { rasa: "shringara", dosha: "pitta" },
  24: { rasa: "shanta", dosha: "kapha" },
  25: { rasa: "shringara", dosha: "pitta" },
  26: { rasa: "shringara", dosha: "pitta" },
  27: { rasa: "adbhuta", dosha: "vata" },
  28: { rasa: "hasya", dosha: "vata" },
  29: { rasa: "veera", dosha: "vata" },
  30: { rasa: "hasya", dosha: "kapha" },
  31: { rasa: "bhakti", dosha: "pitta" },
  32: { rasa: "veera", dosha: "pitta" },
  33: { rasa: "shringara", dosha: "kapha" },
  34: { rasa: "adbhuta", dosha: "vata" },
  35: { rasa: "raudra", dosha: "pitta" },
  36: { rasa: "veera", dosha: "vata" },
  37: { rasa: "shanta", dosha: "vata" },
  38: { rasa: "karuna", dosha: "kapha" },
  39: { rasa: "bhayanaka", dosha: "vata" },
  40: { rasa: "shringara", dosha: "kapha" },
  41: { rasa: "shanta", dosha: "pitta" },
  42: { rasa: "veera", dosha: "pitta" },
  43: { rasa: "adbhuta", dosha: "vata" },
  44: { rasa: "shringara", dosha: "kapha" },
  45: { rasa: "bhayanaka", dosha: "vata" },
  46: { rasa: "adbhuta", dosha: "vata" },
  47: { rasa: "hasya", dosha: "pitta" },
  48: { rasa: "adbhuta", dosha: "vata" },
  49: { rasa: "shanta", dosha: "pitta" },
  50: { rasa: "bhakti", dosha: "kapha" },
  51: { rasa: "shringara", dosha: "pitta" },
  52: { rasa: "shringara", dosha: "kapha" },
  53: { rasa: "veera", dosha: "pitta" },
  54: { rasa: "adbhuta", dosha: "vata" },
  55: { rasa: "bhayanaka", dosha: "kapha" },
  56: { rasa: "adbhuta", dosha: "vata" },
  57: { rasa: "veera", dosha: "pitta" },
  58: { rasa: "hasya", dosha: "pitta" },
  59: { rasa: "veera", dosha: "pitta" },
  60: { rasa: "shanta", dosha: "pitta" },
  61: { rasa: "shringara", dosha: "pitta" },
  62: { rasa: "veera", dosha: "pitta" },
  63: { rasa: "bibhatsa", dosha: "vata" },
  64: { rasa: "adbhuta", dosha: "vata" },
  65: { rasa: "shanta", dosha: "vata" },
  66: { rasa: "hasya", dosha: "vata" },
  67: { rasa: "shanta", dosha: "kapha" },
  68: { rasa: "adbhuta", dosha: "pitta" },
  69: { rasa: "veera", dosha: "kapha" },
  70: { rasa: "shringara", dosha: "pitta" },
  71: { rasa: "hasya", dosha: "kapha" },
  72: { rasa: "shringara", dosha: "vata" },
};
